apiVersion: batch/v1
kind: CronJob
metadata:
  name: cms-create-report-prod
  namespace: cost-management-system-release
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - python send_report.py
            envFrom:
            - secretRef:
                name: cost-management-system-cold-app-secret
            image: asia-southeast2-docker.pkg.dev/moladin-infra-prod/infra-prod/cost-management-system:cronjob-send-report-prod
            imagePullPolicy: Always
            name: cms-create-report
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 13 * * 0'
  suspend: false
