apiVersion: batch/v1
kind: CronJob
metadata:
  name: cms-sync-index-weight
  namespace: cost-management-system-release
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - python sync_index_weight.py
              envFrom:
                - secretRef:
                    name: cost-management-system-cold-app-secret
              image: asia-southeast2-docker.pkg.dev/moladin-infra-prod/infra-prod/cost-management-system:cronjob-sync-index-weight-prod
              imagePullPolicy: Always
              name: cms-sync-index-weight
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
  schedule: '1 5 * * *'
  suspend: True
