apiVersion: batch/v1
kind: CronJob
metadata:
  name: finops-sync-index-weight
  namespace: moladin-finops
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - python v2_sync_index_weight.py
              envFrom:
                - secretRef:
                    name: moladin-finops-cold-app-secret
              image: asia-southeast2-docker.pkg.dev/moladin-infra-prod/infra-prod/moladin-finops:cronjob-sync-index-weight-prod
              imagePullPolicy: Always
              name: finops-sync-index-weight
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: { }
          terminationGracePeriodSeconds: 30
  schedule: '1 5 * * *'
  suspend: True
