apiVersion: batch/v1
kind: CronJob
metadata:
  name: finops-create-report-monthly
  namespace: moladin-finops
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - python v2_send_report.py
            envFrom:
            - secretRef:
                name: moladin-finops-cold-app-secret
            image: asia-southeast2-docker.pkg.dev/moladin-infra-prod/infra-prod/moladin-finops:cronjob-monthly-report
            imagePullPolicy: Always
            name: finops-create-report-monthly
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 13 * * 0'
  suspend: false
