# Generated by Django 4.2.4 on 2023-08-22 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_techfamily_pic_email_alter_techfamily_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('pdf_password', models.CharField(max_length=64)),
                ('metadata', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_log', to='home.techfamily')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_log',
            },
        ),
    ]
