# Generated by Django 4.2.4 on 2023-08-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reportlogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportlogger',
            name='user',
        ),
        migrations.AddField(
            model_name='reportlogger',
            name='created_by',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
