# Generated by Django 4.2.4 on 2023-08-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_reportlogger_user_reportlogger_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogger',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
