# Generated by Django 4.2.4 on 2023-08-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_reportlogger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportlogger',
            name='pdf_password',
            field=models.CharField(max_length=255),
        ),
    ]
