# Generated by Django 4.2.4 on 2023-09-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_reportlogger_pdf_password'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='techfamily',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
