# Generated by Django 4.2.4 on 2023-09-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_indexweight_deleted_at_indexweight_is_deleted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("sku", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gcp_services",
            },
        ),
        migrations.AddConstraint(
            model_name="gcpservices",
            constraint=models.UniqueConstraint(fields=("sku",), name="unique_sku"),
        ),
    ]
