# Generated by Django 4.2.4 on 2023-10-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_indexweight_deleted_at_indexweight_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techfamily',
            name='pic_telp',
            field=models.TextField(default=None, max_length=100, null=True),
        ),
    ]
