# Generated by Django 4.2.4 on 2023-10-03 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_gcpprojects_gcpprojects_unique_project_identity"),
    ]

    operations = [
        migrations.CreateModel(
            name="GCPCosts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_date", models.DateField()),
                ("cost", models.FloatField()),
                ("project_cost", models.FloatField()),
                ("conversion_rate", models.FloatField()),
                (
                    "gcp_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.gcpprojects",
                    ),
                ),
                (
                    "gcp_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.gcpservices",
                    ),
                ),
                (
                    "index_weight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.indexweight",
                    ),
                ),
                (
                    "tech_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.techfamily",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "gcp_costs",
            },
        ),
        migrations.AddConstraint(
            model_name="gcpcosts",
            constraint=models.UniqueConstraint(
                fields=("usage_date", "gcp_project", "gcp_service", "tech_family"),
                name="unique_cost_daily_usage",
            ),
        ),
    ]
