# Generated by Django 4.2.4 on 2023-10-06 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_techfamily_pic_telp'),
        ('home', '0013_gcpcosts_gcpcosts_unique_cost_daily_usage'),
    ]

    operations = [
    ]
