# Generated by Django 4.2.6 on 2023-10-11 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20231006_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='techfamily',
            name='limit_budget',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
