# Generated by Django 4.2.6 on 2023-11-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_techfamily_limit_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gcpcosts",
            name="index_weight",
            field=models.FloatField(),
        ),
    ]
