# Generated by Django 4.2.6 on 2024-01-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_alter_gcpcosts_index_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="BigqueryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.department",
                    ),
                ),
            ],
            options={
                "db_table": "bigquery_user",
            },
        ),
        migrations.CreateModel(
            name="BigqueryCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("usage_date", models.DateField()),
                ("cost", models.FloatField()),
                ("query_count", models.IntegerField()),
                ("metabase_user", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bigquery_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.bigqueryuser",
                    ),
                ),
            ],
            options={
                "db_table": "bigquery_cost",
            },
        ),
        migrations.AddConstraint(
            model_name="bigqueryuser",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
    ]
