# Generated by Django 4.2.6 on 2024-01-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_department_bigqueryuser_bigquerycost_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bigquerycost",
            constraint=models.UniqueConstraint(
                fields=("usage_date", "bigquery_user"),
                name="unique_bigquery_cost_daily_usage",
            ),
        ),
    ]
