# Generated by Django 4.2.6 on 2024-01-12 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_bigquerycost_unique_bigquery_cost_daily_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigquerycost",
            name="gcp_project",
            field=models.ForeignKey(
                default=12,
                on_delete=django.db.models.deletion.PROTECT,
                to="home.gcpprojects",
            ),
            preserve_default=False,
        ),
    ]
