# Generated by Django 4.2.6 on 2024-01-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_bigquerycost_gcp_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="email",
            field=models.EmailField(
                default="devops-engineer@moladin.com", max_length=100
            ),
        ),
    ]
