# Generated by Django 4.2.6 on 2024-01-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_department_email"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bigquerycost",
            name="unique_bigquery_cost_daily_usage",
        ),
        migrations.AddConstraint(
            model_name="bigquerycost",
            constraint=models.UniqueConstraint(
                fields=("usage_date", "bigquery_user", "gcp_project"),
                name="unique_bigquery_cost_daily_usage",
            ),
        ),
    ]
