# Generated by Django 4.2.6 on 2024-01-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_bigquerycost_unique_bigquery_cost_daily_usage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('db_name', models.CharField(max_length=100, null=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=100, null=True)),
                ('project', models.CharField(choices=[('MFI', 'MFI'), ('MDI', 'MDI')], max_length=12)),
                ('environment', models.CharField(choices=[('development', 'DEVL'), ('staging', 'STAG'), ('production', 'PROD')], max_length=12)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.services')),
            ],
            options={
                'db_table': 'services_db',
            },
        ),
        migrations.AddConstraint(
            model_name='servicesdb',
            constraint=models.UniqueConstraint(fields=('db_name', 'project', 'environment'), name='unique_db_name_project_environment'),
        ),
    ]
