# Generated by Django 4.2.6 on 2024-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_servicesdb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesdb',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesdb',
            name='instance_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesdb',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
