# Generated by Django 4.2.6 on 2024-03-27 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_servicesdb_created_at_servicesdb_instance_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TechFamilyCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_date", models.DateField()),
                ("cost", models.FloatField()),
                (
                    "tech_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="home.techfamily",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "tech_family_costs",
            },
        ),
        migrations.AddConstraint(
            model_name="techfamilycost",
            constraint=models.UniqueConstraint(
                fields=("usage_date", "tech_family"), name="unique_tf_cost_daily_usage"
            ),
        ),
    ]
