# Generated by Django 4.2.11 on 2024-06-11 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_techfamilycost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPLabelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('usage_date', models.DateField()),
                ('label_key', models.CharField(max_length=50)),
                ('label_value', models.CharField(max_length=50)),
                ('resource_global_name', models.CharField(max_length=255)),
                ('gcp_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.gcpprojects')),
                ('gcp_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.gcpservices')),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'gcp_label_mappings',
            },
        ),
        migrations.AddConstraint(
            model_name='gcplabelmapping',
            constraint=models.UniqueConstraint(fields=('identifier', 'usage_date'), name='unique_gcp_label_mapping'),
        ),
    ]
