# Generated by Django 4.2.11 on 2024-06-12 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_gcplabelmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPCostResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('cost', models.FloatField()),
                ('project_cost', models.FloatField()),
                ('conversion_rate', models.FloatField()),
                ('index_weight', models.FloatField()),
                ('resource_identifier', models.CharField(max_length=255)),
                ('resource_global_name', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=15)),
                ('billing', models.CharField(max_length=50)),
                ('gcp_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.gcpprojects')),
                ('gcp_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.gcpservices')),
                ('tech_family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.techfamily')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'gcp_cost_resources',
            },
        ),
        migrations.AddConstraint(
            model_name='gcpcostresource',
            constraint=models.UniqueConstraint(fields=('usage_date', 'resource_identifier', 'environment', 'gcp_project', 'gcp_service', 'tech_family'), name='unique_cost_resource_daily_usage'),
        ),
    ]
