# Generated by Django 4.2.15 on 2024-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_gcpcostresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexweight',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='indexweight',
            constraint=models.UniqueConstraint(fields=('environment', 'created_at', 'tech_family'),
                                               name='unique_daily_index_weight'),
        ),
    ]
