openapi: 3.0.3
info:
  title: Cost Management System
  version: 1.0.0
  description: |-
    Efficient cost and budget management are paramount for ensuring the uninterrupted functionality of our business, as well as our various teams and units. This document delves into our comprehensive strategy encompassing five key phases to effectively manage costs and budgets. The approach outlined here will enable us to proactively monitor and control expenses related to Google Cloud Platform (GCP) and other resources. Furthermore, the document highlights the frequency of alerts, indicating that these vital notifications will be disseminated on both a weekly and monthly basis, enhancing our ability to maintain financial transparency and control.
    
    
    Some useful links:
    - [Cost Management System Abstract](https://moladin.atlassian.net/wiki/spaces/IN/pages/739082289/Cost+Management+System)
    - [The source API definition for the CMS](https://bitbucket.org/moladinTech/cost-management-system/src/main/static/schema.yaml)
  termsOfService: https://cost-management-system.moladin.com/
  contact:
    email: devops-engineer@moladin.com
  license:
    name: Moladin
    url: https://cost-management-system.moladin.com/

servers:
  - url: https://cost-management-system.moladin.com
  - url: https://cost-management.moladin.com
  - url: http://0.0.0.0:5005
tags:
  - name: GCP
    description: GCP Cost

  - name: Kubecost
    description: Kubernetes Cost

paths:
  /api/gcp/periodical-cost:
    get:
      operationId: get_periodical_cost
      tags:
        - GCP
      summary: Get Periodical Cost
      description: Get Periodical Cost
      security:
        - basicAuth: [ ]
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date-time
          description: Date / current date (yyyy-mm-dd)
        - in: query
          name: period
          required: true
          schema:
            type: string
            format: string
          description: Fill with weekly or monthly
      responses:
        '200':
          description: No response body
  /api/gcp/index-weight:
    get:
      operationId: get_index_weight
      tags:
        - GCP
      summary: Get Index Weight
      description: Get Index Weight
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: create_index_weight
      tags:
        - GCP
      summary: Create Index Weight
      description: Add new index weight base on living docs
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexWeight'
        required: true
      responses:
        '200':
          description: No response body
  /api/create-report:
    get:
      operationId: create_report
      summary: Create & Generate Report
      description: Create gcp & kubecost report and generate PDF, can send email also
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date-time
          description: Date / current date (yyyy-mm-dd)
        - in: query
          name: period
          required: true
          schema:
            type: string
            format: string
          description: Fill with weekly or monthly
        - in: query
          name: send_mail
          schema:
            type: string
            format: string
          description: Fill with development or stag
      tags:
        - GCP
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/tech-family:
    get:
      operationId: get_tech_family
      tags:
        - General
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: create_tech_family
      tags:
        - General
      summary: Create Tech Family
      description: Create Tech Family
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TechFamily'
        required: true
      responses:
        '200':
          description: No response body
  /api/gcp/services:
    get:
      operationId: get_gcp_services
      summary: Get GCP Services
      description: Get GCP Services
      tags:
        - GCP
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: create_gcp_service
      tags:
        - GCP
      summary: Create GCP Service
      description: Create GCP Service
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GCPService'
        required: true
      responses:
        '200':
          description: No response body
  /api/gcp/projects:
    get:
      operationId: get_gcp_project
      summary: Get GCP projects
      description: Get GCP projects
      tags:
        - GCP
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body

    post:
      operationId: create_gcp_project
      tags:
        - GCP
      summary: Create GCP Project
      description: Create GCP Project
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GCPProject'
        required: true
      responses:
        '200':
          description: No response body

  /api/gcp/costs:
    get:
      operationId: get_gcp_costs
      summary: Get GCP Costs
      description: Get GCP Costs
      tags:
        - GCP
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: create_gcp_cost
      tags:
        - GCP
      summary: Create GCP Cost
      description: Create GCP Cost
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GCPCost'
        required: true
      responses:
        '200':
          description: No response body


  /api/gcp/sync/projects:
    post:
      operationId: sync_gcp_project
      tags:
        - GCP
      summary: Sync GCP Project
      description: Sync GCP Project
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body

  /api/gcp/sync/services:
    post:
      operationId: sync_gcp_service
      tags:
        - GCP
      summary: Sync GCP Service
      description: Sync GCP Service
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body

  /api/gcp/sync/costs:
    post:
      operationId: sync_gcp_service
      tags:
        - GCP
      summary: Sync GCP Service
      description: Sync GCP Service
      security:
        - basicAuth: [ ]
      parameters:
        - in: query
          name: date-start
          required: true
          schema:
            type: string
            format: date-time
          description: Date / current date (yyyy-mm-dd)
      responses:
        '200':
          description: No response body

  /api/kubecost/check-status:
    post:
      operationId: kubecost_check_status_create
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/clusters:
    get:
      operationId: kubecost_clusters_retrieve
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: kubecost_clusters_create
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/deployments:
    get:
      operationId: kubecost_deployments_retrieve
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: kubecost_deployments_create
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/insert-data:
    post:
      operationId: kubecost_insert_data_create
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/namespace-map:
    get:
      operationId: kubecost_namespace_map_retrieve
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: kubecost_namespace_map_create
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/namespaces:
    get:
      operationId: kubecost_namespaces_retrieve
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/kubecost/report:
    get:
      operationId: kubecost_report_retrieve
      tags:
        - Kubecost
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
  /api/services:
    get:
      operationId: services_retrieve
      tags:
        - General
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body
    post:
      operationId: services_create
      tags:
        - General
      security:
        - basicAuth: [ ]
      responses:
        '200':
          description: No response body

  /api/sync/services:
    post:
      operationId: sync_services
      tags:
        - General
      security:
        - basicAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyncService'
        required: true
      responses:
        '200':
          description: No response body
components:
  schemas:
    IndexWeight:
      type: object
      properties:
        value:
          type: integer
          example: 30.12
        environment:
          type: string
          example: "development"
        tech_family_id:
          type: integer
          example: 2

    GCPService:
      type: object
      properties:
        name:
          type: string
          example: "GCP Service"
        sku:
          type: string
          example: "kmzway87aa"

    GCPProject:
      type: object
      properties:
        name:
          type: string
          example: "Moladin project"
        identity:
          type: string
          example: "moladin-project"
        environment:
          type: string
          example: "development"

    GCPCost:
      type: object
      properties:
        usage_date:
          type: string
          example: "2023-01-05"
        cost:
          type: number
          example: 20000.00
        project_cost:
          type: number
          example: 20000.00
        conversion_rate:
          type: number
          example: 15000
        gcp_project_id:
          type: string
          example: "moladin-mof-stag"
        gcp_service_id:
          type: string
          example: "5490-F7B7-8DF6"
        tech_family_slug:
          type: string
          example: "defi_mfi"
        index_weight_id:
          type: integer
          example: 233

    TechFamily:
      type: object
      properties:
        name:
          type: string
          example: "MDI MDI"
        pic:
          type: string
          example: "Jason"
        email:
          type: string
          example: "jason@moladin.com"
        phone_number:
          type: string
          example: "6281223232323"
        limit_budget:
          type: number
          example: 1212121212
        project:
          type: string
          example: "MDI"

    SyncService:
      type: object
      properties:
        project_name:
          type: string
          example: "MFI"
        service_name:
          type: string
          example: "new-service"
        avp:
          type: string
          example: "Tjatur Permadi"
        service_owner:
          type: string
          example: "Pirman Abdurohman"
        platform:
          type: string
          example: "BACKEND"
        tech_family:
          type: string
          example: "PLATFORM"
        vertical_business:
          type: string
          example: "MOFI"
        tribe:
          type: string
          example: "INTOOLS"
        ready_to_scale:
          type: string
          example: "True"
        health_check:
          type: string
          example: "/health"
        probes:
          type: string
          example: "False"
        sonarqube:
          type: string
          example: "True"
        maps_api:
          type: string
          example: "False"
        places_api:
          type: string
          example: "False"
        affinity:
          type: string
          example: "True"
        uptime:
          type: string
          example: "False"
        environment:
          type: string
          example: "devl,stag,prod"
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
